run:
  timeout: 10m
  tests: false

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - exhaustive
    - gci
    - goconst
    - godot
    - godox
    - goheader
    - goimports
    - gomodguard
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unused
    - whitespace

